---
title: Vojtěch Hubner
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

source: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://pat.smallhill.cz" # the base hostname & protocol for your site, e.g. http://example.com

theme: minima 

# Build settings
markdown: kramdown
plugins:
- jekyll-redirect-from
